services:
  postgres:
    image: postgres
    #restart: always
    environment:
      POSTGRES_DB: fishing_hell
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init_scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
  redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis_data:/data
  flexible-mq:
    build: ./flexible-mq/.
  fisher:
    build: ./fisher/.
    depends_on:
      - postgres
    env_file:
      - "./fisher/.env"
  account:
    build: ./account/.
  market:
    build: ./market/.
  metrics:
    build: ./metrics/.
  shop:
    build: ./shop/.
  trading:
    build: ./trading/.
  user-testing:
    build: ./user-testing/.
  dashboard:
    build: ./dashboard/.
    ports:
      - "8080:8080"
    expose:
      - "8080:8080"



volumes:
  db_data:
  redis_data: