// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: proto-files/account.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ticks int32   `protobuf:"varint,3,opt,name=ticks,proto3" json:"ticks,omitempty"`
	Price float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Pole) Reset() {
	*x = Pole{}
	mi := &file_proto_files_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pole) ProtoMessage() {}

func (x *Pole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pole.ProtoReflect.Descriptor instead.
func (*Pole) Descriptor() ([]byte, []int) {
	return file_proto_files_account_proto_rawDescGZIP(), []int{0}
}

func (x *Pole) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pole) GetTicks() int32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

func (x *Pole) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Bait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value float32 `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	Uses  int32   `protobuf:"varint,4,opt,name=uses,proto3" json:"uses,omitempty"`
	Owned int32   `protobuf:"varint,5,opt,name=owned,proto3" json:"owned,omitempty"`
}

func (x *Bait) Reset() {
	*x = Bait{}
	mi := &file_proto_files_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bait) ProtoMessage() {}

func (x *Bait) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bait.ProtoReflect.Descriptor instead.
func (*Bait) Descriptor() ([]byte, []int) {
	return file_proto_files_account_proto_rawDescGZIP(), []int{1}
}

func (x *Bait) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bait) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bait) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Bait) GetUses() int32 {
	if x != nil {
		return x.Uses
	}
	return 0
}

func (x *Bait) GetOwned() int32 {
	if x != nil {
		return x.Owned
	}
	return 0
}

type FishCaught struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Weight     float32 `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	WhenCaught string  `protobuf:"bytes,4,opt,name=whenCaught,proto3" json:"whenCaught,omitempty"` // Use string for timestamps to simplify
	FromPool   string  `protobuf:"bytes,5,opt,name=fromPool,proto3" json:"fromPool,omitempty"`
	Frozen     bool    `protobuf:"varint,6,opt,name=frozen,proto3" json:"frozen,omitempty"`
}

func (x *FishCaught) Reset() {
	*x = FishCaught{}
	mi := &file_proto_files_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FishCaught) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FishCaught) ProtoMessage() {}

func (x *FishCaught) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FishCaught.ProtoReflect.Descriptor instead.
func (*FishCaught) Descriptor() ([]byte, []int) {
	return file_proto_files_account_proto_rawDescGZIP(), []int{2}
}

func (x *FishCaught) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FishCaught) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FishCaught) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *FishCaught) GetWhenCaught() string {
	if x != nil {
		return x.WhenCaught
	}
	return ""
}

func (x *FishCaught) GetFromPool() string {
	if x != nil {
		return x.FromPool
	}
	return ""
}

func (x *FishCaught) GetFrozen() bool {
	if x != nil {
		return x.Frozen
	}
	return false
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cash     float32       `protobuf:"fixed32,2,opt,name=cash,proto3" json:"cash,omitempty"`
	Username string        `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email    string        `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password string        `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Poles    []*Pole       `protobuf:"bytes,6,rep,name=poles,proto3" json:"poles,omitempty"`
	Baits    []*Bait       `protobuf:"bytes,7,rep,name=baits,proto3" json:"baits,omitempty"`
	Fish     []*FishCaught `protobuf:"bytes,8,rep,name=fish,proto3" json:"fish,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_files_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_files_account_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetCash() float32 {
	if x != nil {
		return x.Cash
	}
	return 0
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Account) GetPoles() []*Pole {
	if x != nil {
		return x.Poles
	}
	return nil
}

func (x *Account) GetBaits() []*Bait {
	if x != nil {
		return x.Baits
	}
	return nil
}

func (x *Account) GetFish() []*FishCaught {
	if x != nil {
		return x.Fish
	}
	return nil
}

var File_proto_files_account_proto protoreflect.FileDescriptor

var file_proto_files_account_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x22, 0x56, 0x0a, 0x04, 0x50, 0x6f, 0x6c, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x74, 0x69, 0x63, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x6a,
	0x0a, 0x04, 0x42, 0x61, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x22, 0x9c, 0x01, 0x0a, 0x0a, 0x46,
	0x69, 0x73, 0x68, 0x43, 0x61, 0x75, 0x67, 0x68, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x68, 0x65, 0x6e, 0x43, 0x61, 0x75,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x68, 0x65, 0x6e, 0x43,
	0x61, 0x75, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x6f,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x6f,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x22, 0xf4, 0x01, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x63, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x70, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x65, 0x52, 0x05, 0x70, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x25,
	0x0a, 0x05, 0x62, 0x61, 0x69, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x42, 0x61, 0x69, 0x74, 0x52, 0x05,
	0x62, 0x61, 0x69, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x66, 0x69, 0x73, 0x68, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e,
	0x46, 0x69, 0x73, 0x68, 0x43, 0x61, 0x75, 0x67, 0x68, 0x74, 0x52, 0x04, 0x66, 0x69, 0x73, 0x68,
	0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_account_proto_rawDescOnce sync.Once
	file_proto_files_account_proto_rawDescData = file_proto_files_account_proto_rawDesc
)

func file_proto_files_account_proto_rawDescGZIP() []byte {
	file_proto_files_account_proto_rawDescOnce.Do(func() {
		file_proto_files_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_account_proto_rawDescData)
	})
	return file_proto_files_account_proto_rawDescData
}

var file_proto_files_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_files_account_proto_goTypes = []any{
	(*Pole)(nil),       // 0: protobufs.Pole
	(*Bait)(nil),       // 1: protobufs.Bait
	(*FishCaught)(nil), // 2: protobufs.FishCaught
	(*Account)(nil),    // 3: protobufs.Account
}
var file_proto_files_account_proto_depIdxs = []int32{
	0, // 0: protobufs.Account.poles:type_name -> protobufs.Pole
	1, // 1: protobufs.Account.baits:type_name -> protobufs.Bait
	2, // 2: protobufs.Account.fish:type_name -> protobufs.FishCaught
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_files_account_proto_init() }
func file_proto_files_account_proto_init() {
	if File_proto_files_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_files_account_proto_goTypes,
		DependencyIndexes: file_proto_files_account_proto_depIdxs,
		MessageInfos:      file_proto_files_account_proto_msgTypes,
	}.Build()
	File_proto_files_account_proto = out.File
	file_proto_files_account_proto_rawDesc = nil
	file_proto_files_account_proto_goTypes = nil
	file_proto_files_account_proto_depIdxs = nil
}
